### ISSUE TITLE
Facilitate separation of additions to databases and modifications

### ISSUE THREAD

**Issue by pbkeating** [alexsanjoseph/compareDF#20] opened 2019-05-02 07:05 UTC
Hello Alex,

I've been regularly using and finding the compareDF package to be very helpful since I found it last November.

The html output is really helpful, but wondered if it would be possible to add functionality to produce separate outputs for additions to databases and for modifications? When many additions and modifications have been made between two versions of a database and then both of these types of outputs are mixed, it makes it more difficult to use the output. I'm currently adapting the comparison_df output, but great if it was a built in functionality.

Thanks again for this package!
Patrick

**Comment by alexsanjoseph** [comment] 2019-05-02 07:47
@pbkeating - can you try a group by by `chng_type` on the `$comparison_df` object? Will that solve the problem?

**Comment by pbkeating** [comment] 2019-05-02 07:58
Hi,

Thanks for that. Tried it, but as `chng_type` is binary and applies to additions, removals and modifications, it doesn't allow for easy separation. That would be a great way of doing it though if there were different `chng_type` for additions, subtractions and modifications.

Thanks,
Patrick

**Comment by alexsanjoseph** [comment] 2019-05-02 09:33
Can you try installing the package from the add_grouping_type branch? In that add a new argument, `add_grouping_type=TRUE` to the `compare_df` call. Does this help you?

@pbkeating

**Comment by pbkeating** [comment] 2019-05-02 12:45
Apologies for delay in getting back. Got involved in other activities.
I tried to install the `install_github("alexsanjoseph/compareDF", ref = "add_grouping_type")` package but when I tried to run it, I got the following error

`Error in compare_df(x, x_ref, c("id"), limit_html = 700, add_grouping_type = TRUE) : 
  unused argument (add_grouping_type = TRUE)`

I examined the code and couldn't find the argument add_grouping_type. See txt file attached.
[comparedf_function.txt](https://github.com/alexsanjoseph/compareDF/files/3138035/comparedf_function.txt)

**Comment by alexsanjoseph** [comment] 2019-05-02 12:51
Are you sure the installation went fine? (Try restarting R, maybe?) The function is here jn this branch - https://github.com/alexsanjoseph/compareDF/blob/add_grouping_type/R/fnsComparison.R

**Comment by pbkeating** [comment] 2019-05-02 13:33
Thanks. I restarted R and could run the function. Thanks for the speedy reactions on this!
I ran it and see the output below. Unfortunately, the numbers of additions and removals identified by the `change_summary` variable are different from the add_grouping_type.

Worth adding in a `removed` grouping?

![20190502_152533 1](https://user-images.githubusercontent.com/20238915/57078808-4610cb00-6cef-11e9-98ad-be5675da0e39.jpg)

**Comment by pbkeating** [comment] 2019-05-02 13:33
Just realised that removed is there. Thanks!

**Comment by alexsanjoseph** [comment] 2019-05-02 13:38
I added the group calculation using a heuristic that I thought would work. Can you add a small reproducible example which shows the mismatch between the change summary and the grouping?

**Comment by pbkeating** [comment] 2019-05-02 13:54
I tried out a simple example and it seems to have worked as expected...not sure why it was not the case with the dataset that I have used

a <- data.frame(id = c("t1","t2","t3","t4","t5"), 
                gender = c("m","f","m","f", "f"),
                age = c(10, 13, 14, 90, 20))

b <- data.frame(id = c("t1","t4","t5", "t6", "t7", "t8", "t9"), 
                gender = c("f","f","m","f", "f", "m", "m"),
                age = c(10, 93, 20, 15, 20, 35, 56))

test <- compareDF::compare_df(b, a, c("id"), add_grouping_type = TRUE)

test$comparison_df

**Comment by pbkeating** [comment] 2019-05-02 14:00
I selected 12 variables when comparing... could that affect it?

**Comment by alexsanjoseph** [comment] 2019-05-02 14:39
I have no idea - my internal test case also seem to have worked, hence I did the commit. This should be some sort of edge case. Hopefully you can find out what's going on with a smaller dataset, don't know what to do otherwise

**Comment by pbkeating** [comment] 2019-05-02 21:24
Hi again. I tested with just 4 variables and it got closer to the real situation, but not completely there.
It sometimes misclassifies newly added rows with modified rows and some removed rows as modified rows.

![20190502_231309 1](https://user-images.githubusercontent.com/20238915/57107317-f69ebf00-6d2f-11e9-80b2-1404030986e7.jpg)

**Comment by alexsanjoseph** [comment] 2019-05-03 04:20
Hmmm there is definitely a bug in there somewhere. If you are able to find me a few cases that will be amazing. In the meantime I'll try if I can reproduce it myself in a bit. Keeping the ticket open till then.

**Comment by pbkeating** [comment] 2019-05-03 13:14
Wondering if has anything to do with inclusion of dates as variables.  I was using three date variables and wondered if that could have made an impact.

Thanks again!

**Comment by alexsanjoseph** [comment] 2019-05-05 05:59
@pbkeating - Can you share a snippet of the data that you're working with (maybe anonymized?)

**Comment by pbkeating** [comment] 2019-05-06 08:37
Hi,

I'll do my best to get you a similar dataset over the coming days. Thank you for the follow-up on this!

**Comment by alexsanjoseph** [comment] 2019-06-05 04:42
@pbkeating - were you able to get a reprex for this? If not I'll have to close this :/

**Comment by pbkeating** [comment] 2019-06-05 06:13
Hi,

No, I didn't manage it. Thanks for all your help and responsiveness.

Best,
Patrick

**Comment by alexsanjoseph** [comment] 2019-06-05 08:35
Thanks @pbkeating, feel free to create a new issue if this is a problem. I'm not merging the branch for now, since it seems to have issues

**Closed by alexsanjoseph** 2019-06-05 08:35 UTC
Labels: bug
